config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'movies#index'
  resources :movies
  
  get '/likes/:movie_id' => 'movies#like_movie'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
    mount_uploader :image_path, ImageUploader
    
    has_many :likes
    has_many :users, through: :likes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         has_many :likes
         has_many :movies, through: :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def js_authenticate_user!
      render js:"location.href='/users/sign_in';" unless user_signed_in? 
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :js_authenticate_user!, only: [:like_movie]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)
    @movie.user_id = current_user.id
    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like_movie
    p params 
    # 현재 유저와 params에 담긴  movie간의
    # 좋아요 관계를 설정한다.
    
    # 만약에 현재 로그인한 유저가 이미 좋아요를 눌렀을 경우
    # 해당 Like 인스턴스 삭제
    # 새로 누른경우
    # 좋아요 관계 설정
    
    @like = Like.where(user_id: current_user.id, movie_id: params[:movie_id]).first
    if @like.nil?
      @like = Like.create(user_id: current_user.id, movie_id: params[:movie_id])
    else
      @like.destroy
    end
    
    puts "좋아요 설정 완료"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title,:genre,:director,:actor,:description,:image_path)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WatchaApp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application'%>
  </head>

  <body>
    <% flash.each do |k,v| %>
    <div class="alert alert-<%= k%>"><%= v%></div>
    <% end  %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for(movie) do |f| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="form-group">
     <%= f.label :title %>
     <%= f.text_field :title, class: "form-control" %> 
  </div>  

   <div class="form-group">
     <%= f.label :genre %>
     <%= f.text_field :genre, class: "form-control" %> 
  </div>
   <div class="form-group">
     <%= f.label :director %>
     <%= f.text_field :director, class: "form-control" %> 
  </div>
   <div class="form-group">
     <%= f.label :actor %>
     <%= f.text_field :actor, class: "form-control" %> 
  </div>
  
     <div class="form-group">
     <%= f.label :description %>
     <%= f.text_area :description, class: "form-control" %> 
  </div>
  
  <div class="form-group">
     <%= f.label :image_path %>
     <%= f.file_field :image_path, class: "form-control" %> 
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1 id="title">Movies</h1>
<div id= "title" class="row">
<% @movies.each do |movie| %>
<div class="card col-md-3">
  <img class="card-img-top" src="<%= movie.image_path.thumb.url%>" alt="<%= movie.title%>">
  <div class="card-body">
    <h5 class="card-title"><span><%= movie.title%></span></h5>
    <p class="card-text">장르 : <%= movie.genre%></p>
    <p class="card-text">주연배우 : <%= movie.actor%></p>
    <p class="card-text">감독 : <%= movie.director%></p>
    <%= link_to '영화 정보보기', movie_path(movie), class: 'btn btn-primary' %>
  </div>
</div>
<%  end %>
</div>
<br>

<%= link_to 'New Movie', new_movie_path %>
<hr>
<% if user_signed_in? %>
<!-- 로그인된 상태  -->
<%= current_user.email%>
<%= link_to '로그 아웃', destroy_user_session_path, method: "delete" %>
<% else %>
<!-- 로그아웃된 상태  -->
<%= link_to '로그인', new_user_session_path %>
<%  end %>

<script> 

// var func = function(){
//     alert("하하");
// }

// function func1(){
//     alert("하이");
// }

// var btn = document.getElementsByClassName("btn")[1];
// btn.addEventListener("mouseover", func1);

// var btn2 = document.getElementsByClassName("btn")[0];
// btn2.onmouseover = func;

// // 먼저 선언되어 있단 함수를 이벤트 핸들러로 사용할 경우
// // 함수 이름만 적어서 사용한다.
// // 함수이름() <- 이 형태는 함수의 실행을 의미한다.

//버튼(요소)에 마우스를 오버(이벤트) 했더니(이벤트리스너)
// 그 위에 있던 글자들(요소)이 갑자기 이상한 글자로 변해버렸다.(이벤트 핸들러)
// var mtitle = document.getElementsByClassName("card-title")[0].innerText

// var btn = document.getElementsByClassName("btn")[0];
// btn.addEventListener("mouseover",function(){
//   var title = document.getElementsByClassName("card-title")[0];
//   console.dir(title);
//   title.innerText = "건드리지마";
// });
// btn.addEventListener("mouseleave",function(){
//   var title = document.getElementsByClassName("card-title")[0];
  
//   title.innerText = mtitle;
// });


// 버튼(요소)에 마우스를 올리면(이벤트, 이벤트 리스너) 
//해당 버튼의 class가 btn btn-danger로 변함
// var btn = document.getElementsByClassName("btn")[0];
// btn.addEventListener("mouseover", function(){
//   btn.setAttribute("class","btn btn-danger disabled");
// })
// btn.addEventListener("mouseout", function(){
//   btn.setAttribute("class","btn btn-info");
// })


</script>

app/views/movies/like_movie.js.erb
alert("좋아요");

//좋아요가 취소된 경우
// 좋아요 취소버튼 -> 좋아요 버튼으로 바꿔준다.
if (<%= @like.frozen? %>) {
$('.like').text("좋아요").toggleClass("btn-info btn-warning text-white");


}else{
//좋아요가 새로눌린 경우
// 좋아요 버튼 -> 좋아요 취소버튼으루~!~!

$('.like').text("좋아요 취소").toggleClass("btn-info btn-warning text-white");
}

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<h1><%= @movie.title%></h1>
<hr>
<p><%= @movie.description%></p>
<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>
<hr>
<button class="btn btn-info like">좋아요</button>
<script>
$(document).on('ready', function(){
    $('.like').on('click', function(){
        console.log("like!!!");
        $.ajax({
            url: '/likes/<%= @movie.id%>'
        });
    });
});
</script>